#!/bin/bash
# Shortcuts
alias ll='ls -lh'
alias la='ls -lhA'
alias l='clear'
alias cls='clear'
alias c='clear'
alias x='exit'
alias q='exit'
alias i='sudo -i'
alias refresh='xrandr --output eDP1 --mode 1920x1080 --auto'

# git
alias g='git'
alias gs='git status';

#Github Shortcuts & Functions
gi(){
  # Initalize a fresh online Github Repository.
  if [ -z "$GITREPO" ]; then
    echo "Great Scott! You forgot to tell me the repo's name."
  else
    GITUSER=anchortenant
    GITREPO="$*"
    touch README.md
    git init
    git add README.md
    git commit -m "first commit"
    git remote add origin git@github.com:"$GITUSER"/"$GITREPO".git
    git push -u origin master
    printf "\r Git Initialized"
  fi
}
alias gs='git status'
ga(){
  # Add all files to Git VCS que unless specifically stated.
  FILEADD=( "$@" )
  if [ -z "$FILEADD" ]; then
    echo "all changes added to que"
    git add -Av
  else
    echo "added ${FILEADD[*]} to que"
    git add "${FILEADD[@]}";
  fi
  printf "\r"
  echo "Great Scott!! There's changes in the time-space continuum!"
}
gchk(){
  # Remove flagged changes from Git
  git checkout -- "$@"
}
gm(){
  # Commit added changged to current working directory branch.
  # Use default error debuuging message for commit description unless otherwise stated.
  MSG="Commited changes ready to push"
  FILEMODS="$*"
  if [ -z "$FILEMODS" ]; then
    git commit -m "Error debugged \& fixed"
    echo "$MSG"
  else
    git commit -m "$FILEMODS"
  fi
  printf "\r"
  echo "$MSG"
}
gp(){
  # Push commited local branch to Github repository's master branch unless otherwise stated.
  REPO="$1"
  if [ -z "$REPO" ]; then
    echo "Commiting changes to master"
    git push origin master
  else
    echo "Commiting changes to $REPO"
    git push origin "$REPO"
  fi
  printf "\n"
	echo "Changes sucessfully uploaded"
}
gc() { 
	git clone https://github.com/anchortenant/"$1" 
}

# pacman
alias update='sudo pacman -Sy'
alias upgrade='sudo pacman -Syuu'
alias install='packer --noedit --noconfirm -S'
alias remove='sudo pacman -Rsc'
alias search='packer -Ss'
alias pacman='sudo pacman'
alias pinfo='packer -Si'
# packer
alias packer='packer --noedit'

# nano
alias xapt='sudo nano /etc/apt/sources.list'
alias xaliases='nano ~/.dotfiles/bash.d/aliases && echo "reloading bash" && source ~/.bashrc'
alias nanorc='sudo nano /etc/nanorc'
alias sshd='sudo nano /etc/ssh/sshd_config && echo "restarting sshd" && sleep 2 && sudo service ssh restart'
alias xkeys='nano ~/.ssh/authorized_keys'
alias xnet='sudo nano /etc/network/interfaces'
alias xtime='sudo nano /etc/ntp.conf'
alias xee='sudo nano /etc/ee/ee.conf'
alias xtables='sudo nano /etc/iptables.conf'
alias xfunctions='sudo nano /var/www/affinityskin.com.au/htdocs/wp-content/themes/x-child/functions.php'
alias xgrub='sudo nano /etc/default/grub && sudo update-grub'
alias xbash="source ~/.bashrc"

# commands
alias pip='sudo -H pip'
alias pip2='sudo -H pip2'
alias visudo='sudo visudo'
alias service='sudo service'
alias ufw='sudo ufw'
alias shutdown='sudo shutdown now'
alias reboot='sudo reboot'
alias nginx='sudo nginx'
alias cp='sudo cp -av'
alias mv='sudo mv'
alias rm='sudo rm -rf'
alias chown='sudo chown -R loki:loki'
alias chownr='sudo chown -R root:root'
alias chmod='sudo chmod -R'
alias wpscan='sudo ruby ~/wpscan/wpscan.rb'
alias ifconfig='sudo ifconfig'
alias cat='sudo cat'
alias tail='sudo tail'
alias mount='sudo mount'
alias umount='sudo umount'
alias chroot='sudo chroot'
alias ln='sudo ln -s'
alias unzip='sudo unzip'

# locations
alias www='cd /var/www'
alias devd='cd /var/www/dev.affinityskin.com.au/htdocs'
alias wwwd='cd /var/www/dev.affinityskin.com.au/htdocs/wp-content'
alias wwws='cd /var/www/staging.affinityskin.com.au/htdocs/wp-content'
alias wwww='cd /var/www/affinityskin.com.au/htdocs/wp-content'
alias wwwf='cd /var/www/fresh.affinityskin.com.au/htdocs/wp-content'
alias wwwx='cd /var/www/xfresh.affinityskin.com.au/htdocs/wp-content'
alias www2='cd /var/www/22222/htdocs'
alias log='cd /var/log'
alias xnginx='cd /etc/nginx'
alias ntest='nginx -t'
alias nreload='sudo service nginx reload'
alias nstop='sudo service nginx stop'
alias nsstart='sudo service nginx start'
alias ipwan='curl ifconfig.me/ip'

# SSH Locations
alias psi='TERM=xterm ssh loki@192.168.0.10'
alias epsilon='TERM=xterm ssh -p 200 loki@ts.loginto.me'
alias omega='TERM=xterm ssh -p 250 root@ts.loginto.me'
alias cerberus='TERM=xterm ssh loriezn@cerberus.seedboxes.cc'


alias log='cd /var/log'
alias xnginx='cd /etc/nginx'
alias ntest='nginx -t'
alias nreload='sudo service nginx reload'

