#!/usr/bin/env bash

# Shortcuts
alias ls='ls --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'
alias ll='ls -l --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'
alias la='ls -la --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'
alias grep='grep --color=tty -d skip'
alias df='df -h'                          # human-readable sizes
alias du='du -hS'
alias l='clear'
alias c='cat'
alias x='exit'
alias s='sublime'
alias i='sudo -i'
alias r='xrandr --output eDP1 --mode 2048x1152 --auto'
alias refresh='xrandr --output eDP1 --mode 2048x1152 --auto'
alias bb="cd $HOME/.bash.d"
alias cd..='cd ..'

# pacman
alias update='sudo pacman -Sy'
alias upgrade='sudo pacman -Syuu'
alias install='packer --noedit --noconfirm'
alias remove='sudo pacman -Rsc'
alias search='packer -Ss'
alias pacman='sudo pacman'
alias pinfo='packer -Si'
# packer
alias packer='packer --noedit'

# subl3
alias xbash='subl3 /home/loki/.bashrc && source /home/loki/.bashrc && echo "BASH Reloaded"'
alias b='subl3 /home/loki/.bashrc && source /home/loki/.bashrc && echo "BASH Reloaded"'
alias xxbash='source /home/loki/.bashrc && echo "BASH Reloaded"'
alias xb='source /home/loki/.bashrc && echo "BASH Reloaded"'
alias xaliases='subl3 /home/loki/.bash_aliases && source /home/loki/.bashrc && echo "BASH Reloaded"'
alias a='subl3 /home/loki/.bash.d/aliases && source /home/loki/.bashrc && echo "BASH Reloaded"'
alias nanorc='sudo subl3 /etc/nanorc'
alias h='sudo subl3 /etc/hosts'

# commands
alias visudo='sudo visudo'
alias service='sudo service'
alias shutdown='sudo shutdown now'
alias reboot='sudo reboot'

# File Utils
alias cp='sudo cp -av'
alias mv='sudo mv'
alias rm='sudo rm -r'
alias ln='sudo ln -s'
alias mkdir='mkdir -p'
alias touch='touch'

# File Permissions
alias chmod='sudo chmod -R'
alias chown='sudo chown -R $USER:$USER'

# Compression
alias cat='sudo cat'
alias tail='sudo tail'
alias unzip='sudo unzip'

# Networking
alias ufw='sudo ufw'
alias ifconfig='sudo ifconfig'
alias ipwan='dig +short myip.opendns.com @resolver1.opendns.com'
alias iptables='sudo iptables'
alias wpscan='sudo ruby /home/loki/wpscan/wpscan.rb'


# Nginx
alias nginx='sudo nginx'
alias n='cd /etc/nginx'
alias t='sudo nginx -t; sudo systemctl restart nginx.service'
alias www='cd /var/www/'
alias log='cd /var/log/nginx/'
alias k='subl3 /home/loki/.ssh/authorized_keys'
alias kn='subl3 /home/loki/.ssh/known_hosts'
alias sshd='sudo subl3 /etc/ssh/sshd_config; sudo systemctl restart sshd.service; echo "SSH Reloaded"'





# subl3
alias xapt='sudo subl3 /etc/apt/sources.list'
alias xaliases='subl3 ~/.dotfiles/bash.d/aliases && echo "reloading bash" && source ~/.bashrc'
alias xi3='subl3 ~/.i3/config'
alias xtermite='subl3 ~/.config/termite/config'
alias sshd='sudo subl3 /etc/ssh/sshd_config && echo "restarting sshd" && sleep 2 && sudo service ssh restart'
alias xkeys='subl3 ~/.ssh/authorized_keys'
alias xnet='sudo subl3 /etc/network/interfaces'
alias xtime='sudo subl3 /etc/ntp.conf'
alias xee='sudo subl3 /etc/ee/ee.conf'
alias xtables='sudo subl3 /etc/iptables.conf'
alias xfunctions='sudo subl3 /var/www/affinityskin.com.au/htdocs/wp-content/themes/x-child/functions.php'
alias xgrub='sudo subl3 /etc/default/grub && sudo update-grub'
alias xbash="source ~/.bashrc"

# commands
alias gparted='sudo gparted &'
alias pip='sudo -H pip'
alias pip2='sudo -H pip2'
alias visudo='sudo visudo'
alias service='sudo service'
alias ufw='sudo ufw'
alias shutdown='sudo shutdown now'
alias reboot='sudo reboot'
alias nginx='sudo nginx'
alias cp='sudo cp -av'
alias mv='sudo mv'
alias rm='sudo rm -rf'
alias chown='sudo chown -R loki:loki'
alias chownr='sudo chown -R root:root'
alias chmod='sudo chmod -R'
alias wpscan='sudo ruby ~/wpscan/wpscan.rb'
alias ifconfig='sudo ifconfig'
alias cat='sudo cat'
alias tail='sudo tail'
alias mount='sudo mount'
alias umount='sudo umount'
alias chroot='sudo chroot'
alias ln='sudo ln -s'
alias unzip='sudo unzip'

# locations
alias www='cd /var/www'
alias devd='cd /var/www/dev.affinityskin.com.au/htdocs'
alias wwwd='cd /var/www/dev.affinityskin.com.au/htdocs/wp-content'
alias wwws='cd /var/www/staging.affinityskin.com.au/htdocs/wp-content'
alias wwww='cd /var/www/affinityskin.com.au/htdocs/wp-content'
alias wwwf='cd /var/www/fresh.affinityskin.com.au/htdocs/wp-content'
alias wwwx='cd /var/www/xfresh.affinityskin.com.au/htdocs/wp-content'
alias www2='cd /var/www/22222/htdocs'
alias log='cd /var/log'
alias xnginx='cd /etc/nginx'
alias ntest='nginx -t'
alias nreload='sudo service nginx reload'
alias nstop='sudo service nginx stop'
alias nsstart='sudo service nginx start'
alias ipwan='curl ifconfig.me/ip'

alias log='cd /var/log'
alias xnginx='cd /etc/nginx'
alias ntest='nginx -t'
alias nreload='sudo service nginx reload'

# SSH Locations
alias epsilon='TERM=xterm ssh -p 170 loki@14.202.176.121'
alias proxima='TERM=xterm ssh -p 200 loki@14.202.176.121'
alias omega='TERM=xterm ssh -p 250 loki@14.202.176.121'
alias mediahubzn='TERM=xterm ssh -p 150 loki@14.202.176.121'
alias cerberus='TERM=xterm ssh loriezn@cerberus.seedboxes.cc'


alias veewee='bundle exec veewee'
