#!/usr/bin/env bash
set -e

echo "Installing prerequisites for packer..."
sudo pacman -S base-devel fakeroot jshon expac

echo "Installing base packages..."
packer --noconfirm --noedit -S \
  bash-completion \
  termite-git

echo "Installing Python dependencies..."
packer --noconfirm --noedit -S \
  python-basiciw \
  python-netifaces \
  python-yaml \
  python-pillow \
  python-urllib3 \
  python2-suds

echo "Installing window manager dependencies..."
packer --noconfirm --noedit -S \
  xcb-util-keysyms \
  xcb-util-wm \
  xcb-util-cursor \
  yajl \
  startup-notification \
  libev

echo "Installing tools..."
packer --noconfirm --noedit -S \
  i3-gaps-git \
  i3lock \
  i3blocks-gaps-git \
  gsimplecal \
  thunderbird \
  thunderbird-enigmail \
  thunderbird-lightning-bin \
  feh \
  acpi \
  xorg \
  xorg-xinit \
  xorg-server-utils \
  xdotool \
  xf86-video-intel \
  mesa-libgl \
  lib32-mesa-libgl \
  pulseaudio-ctl \
  pavucontrol \
  gnome-keyring \
  alsa-tools \
  alsa-utils 

packer --noconfirm --noedit -S \
  networkmanager \
  nm-connection-editor \
  network-manager-applet \
  networkmanager-openvpn \
  imagemagick \
  dunst \
  python \
  python-pip \
  python2-pip \
  compton-git \
  ttf-font-awesome \
  ohsnap \
  ttf-hack \
  powerline-fonts-git \
  thunar \
  weechat \
  thunar-archive-plugin \
  file-roller \
  tumbler \
  eog \
  numix-themes \
  numix-icon-theme-git \
  tk \
  aspell-en \
  evince \
  rofi \
  libmtp \
  gvfs-mtp \
  vim-airline \
  vim-fugitive \
  vim-gruvbox-git \
  vim-airline-gruvbox-git \
  vim-youcompleteme-git \
  vim-gitgutter-git \
  xtitle-git \
  openssh \
  arandr \
  xclip \
  xedgewarp-git \
  unclutter-xfixes-git \
  thefuck \
  youtube-dl \
  slop \
  maim \
  neofetch-git \
  w3m \
  htop \
  bluez \
  bluez-utils \
  pulseaudio-bluetooth \
  blueman \
  redshift \
  firefox \
  chromium \
  sublime-text-dev \
  lm_sensors

echo "Installing some python stuff..."
packer --noconfirm --noedit -S \
  python-pillow \
  python-urllib3

echo "Installing some perl stuff..."
packer --noconfirm --noedit -S \
  perl-anyevent-i3 \
  perl-json-xs \
